version: '3.8'

services:
  # База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: prod_analysis_postgres
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: $${DB_USERNAME}
      POSTGRES_PASSWORD: $${DB_PASSWORD}
      POSTGRES_DB: $${DB_NAME}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prod_analysis_network

networks:
  prod_analysis_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local